apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-azuredisk
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: managed-csi
  csi:
    driver: disk.csi.azure.com
    readOnly: false
    volumeHandle: /subscriptions/d9a26e59-ea41-48ff-9af8-3a62419043b5/resourceGroups/MC_rg-kub_kub108_southcentralus/providers/Microsoft.Compute/disks/myAKSDisk
    volumeAttributes:
      fsType: ext4